INSERT INTO USER (USER_ID, USER_LOGIN, USER_NAME, USER_SURNAME, USER_ROLE) VALUES (1l, 'Test_Login_1', 'Test_Name_1', 'Test_Surname_1', 'CUSTOMER');

INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_1, BOOK_TYPE, LANGUAGE, PAGES, RELEASE_YEAR, PUBLISHING_HOUSE, ISBN, COPIES, GENRE_TYPE) VALUES (1l, 'Test_title_1', 'Test_author_1', 'BOOK', 'EN', 150, 1960, 'P_H', 'ISBN', 0, 'BIOGRAPHY');

