INSERT INTO USER (USER_ID, USER_LOGIN, USER_NAME, USER_SURNAME, USER_ROLE) VALUES (1l, 'Test_Login', 'Test_Name', 'Test_Surname', 'CUSTOMER');

INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_1, BOOK_TYPE, LANGUAGE, PAGES, RELEASE_YEAR, PUBLISHING_HOUSE, ISBN, COPIES, GENRE_TYPE) VALUES (1l, 'Test_title_1', 'Test_author_1', 'BOOK', 'EN', 150, 1960, 'P_H', 'ISBN', 12, 'BIOGRAPHY');
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_1, BOOK_TYPE, LANGUAGE, PAGES, RELEASE_YEAR, PUBLISHING_HOUSE, ISBN, COPIES, GENRE_TYPE) VALUES (2l, 'Test_title_2', 'Test_author_2', 'BOOK', 'EN', 120, 1970, 'P_H', 'ISBN', 3, 'FICTION');
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_1, BOOK_TYPE, LANGUAGE, PAGES, RELEASE_YEAR, PUBLISHING_HOUSE, ISBN, COPIES, GENRE_TYPE) VALUES (3l, 'Test_title_3', 'Test_author_3', 'BOOK', 'EN', 130, 1980, 'P_H', 'ISBN', 7, 'NOVEL');

INSERT INTO RENTAL_RECORD (RENTAL_RECORD_ID, BOOK_ID, CUSTOMER_ID, RENTAL_RECORD_STATUS) VALUES (1l, 1l, 1l, 'RENTED');
INSERT INTO RENTAL_RECORD (RENTAL_RECORD_ID, BOOK_ID, CUSTOMER_ID, RENTAL_RECORD_STATUS) VALUES (2l, 2l, 1l, 'RENTED');
INSERT INTO RENTAL_RECORD (RENTAL_RECORD_ID, BOOK_ID, CUSTOMER_ID, RENTAL_RECORD_STATUS) VALUES (3l, 3l, 1l, 'RENTED');
INSERT INTO RENTAL_RECORD (RENTAL_RECORD_ID, BOOK_ID, CUSTOMER_ID, RENTAL_RECORD_STATUS) VALUES (4l, 4l, 1l, 'RESERVED');